HACK: Workaround TypeScript issue
This appeared out of noewhere and we don't know why:
src/server/helpers/request.js(2,1): error TS9006: Declaration emit for this file requires using private name 'StaticEventEmitterOptions' from module '"events"'. An explicit type annotation may unblock declaration emit.
src/server/helpers/request.js(2,1): error TS9006: Declaration emit for this file requires using private name '_DOMEventTarget' from module '"events"'. An explicit type annotation may unblock declaration emit.
src/server/helpers/request.js(2,1): error TS9006: Declaration emit for this file requires using private name '_NodeEventTarget' from module '"events"'. An explicit type annotation may unblock declaration emit.